<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\comissao\comissao.csproj" />
    <ProjectReference Include="..\..\src\estoque\estoque.csproj" />
    <ProjectReference Include="..\..\src\juros\juros.csproj" />
  </ItemGroup>

</Project>
